# -*- coding: utf-8 -*-
"""20210522_Advanced_Mathematics_CW.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/15lgbFNqiHt8vb1S9h6Kotvy1ktbVE1Ws
"""

#Question 1:a)

import sympy as sym
import numpy as np
import matplotlib.pyplot as plt

x = sym.symbols('x')

def f(x):
    if 0 > x >= -np.pi:
        return x ** 2 + 1
    elif 0 <= x <= np.pi:
        return x * np.exp(-1)

xValues = np.arange(-4 * np.pi, 4 * np.pi, 0.01)
yValues = [f(x) for x in xValues]

plt.title("PF")
plt.xlabel=("y")
plt.ylabel=("x")
plt.plot(xValues, yValues)
plt.show()
